import { Application } from '@hotwired/stimulus';
import Hellotext from './hellotext.js';
import FormController from './controllers/form_controller.js';
import MessageController from './controllers/message_controller.js';
import WebChatEmojiController from './controllers/webchat/emoji_picker_controller.js';
import WebchatController from './controllers/webchat_controller.js';
var application = Application.start();
application.register('hellotext--form', FormController);
application.register('hellotext--webchat', WebchatController);
application.register('hellotext--webchat--emoji', WebChatEmojiController);
application.register('hellotext--message', MessageController);
window.Hellotext = Hellotext;
export default Hellotext;